/**
 * Protocol constants matching the C server implementation
 */

// Protocol version
export const PROTOCOL_V1 = 0x01

// Packet types
export const PACKET_TYPE = {
  // Service
  PING: 10,
  PONG: 11,

  // Authentication
  LOGIN_REQUEST: 100,
  LOGIN_RESPONSE: 100,
  R_LOGIN_OK: 101,
  R_LOGIN_NOT_OK: 102,

  // Registration
  SIGNUP_REQUEST: 200,
  SIGNUP_RESPONSE: 200,
  R_SIGNUP_OK: 201,
  R_SIGNUP_NOT_OK: 202,

  // Table Management
  CREATE_TABLE_REQUEST: 300,
  CREATE_TABLE_RESPONSE: 300,
  R_CREATE_TABLE_OK: 301,
  R_CREATE_TABLE_NOT_OK: 302,
  PACKET_TABLES: 500,

  // Game Flow
  JOIN_TABLE_REQUEST: 400,
  JOIN_TABLE_RESPONSE: 400,
  R_JOIN_TABLE_OK: 401,
  R_JOIN_TABLE_NOT_OK: 402,
  R_JOIN_TABLE_FULL: 403,
  ACTION_REQUEST: 450,
  ACTION_RESULT: 451,
  UPDATE_BUNDLE: 460,
  RESYNC_REQUEST: 470,
  RESYNC_RESPONSE: 471,

  // Game State
  UPDATE_GAMESTATE: 600,

  // Leave Table
  LEAVE_TABLE_REQUEST: 700,
  LEAVE_TABLE_RESPONSE: 700,

  // Scoreboard
  GET_SCOREBOARD: 800,
  SCOREBOARD_RESPONSE: 800,

  // Friend List
  GET_FRIENDLIST: 900,
  FRIENDLIST_RESPONSE: 900,

  // Friend Management
  ADD_FRIEND: 910,
  R_ADD_FRIEND_OK: 911,
  R_ADD_FRIEND_NOT_OK: 912,
  R_ADD_FRIEND_ALREADY_EXISTS: 913,

  INVITE_FRIEND: 920,
  R_INVITE_FRIEND_OK: 921,
  R_INVITE_FRIEND_NOT_OK: 922,
  R_INVITE_ALREADY_SENT: 923,

  ACCEPT_INVITE: 930,
  R_ACCEPT_INVITE_OK: 931,
  R_ACCEPT_INVITE_NOT_OK: 932,

  REJECT_INVITE: 940,
  R_REJECT_INVITE_OK: 941,
  R_REJECT_INVITE_NOT_OK: 942,

  GET_INVITES: 950,
  R_GET_INVITES_OK: 951,
  R_GET_INVITES_NOT_OK: 952,

  GET_FRIEND_LIST: 960,
  R_GET_FRIEND_LIST_OK: 961,
  R_GET_FRIEND_LIST_NOT_OK: 962
} as const

// Export individual constants for convenience
export const PACKET_ACTION_REQUEST = 450
export const PACKET_ACTION_RESULT = 451
export const PACKET_UPDATE_GAMESTATE = 600
export const PACKET_UPDATE_BUNDLE = 460
export const PACKET_JOIN_TABLE = 400
export const PACKET_LEAVE_TABLE = 700
export const PACKET_BALANCE_UPDATE = 970

// Response codes
export const RESPONSE_CODE = {
  R_LOGIN_OK: 101,
  R_LOGIN_NOT_OK: 102,
  R_SIGNUP_OK: 201,
  R_SIGNUP_NOT_OK: 202,
  R_CREATE_TABLE_OK: 301,
  R_CREATE_TABLE_NOT_OK: 302,
  R_JOIN_TABLE_OK: 401,
  R_JOIN_TABLE_NOT_OK: 402,
  R_JOIN_TABLE_FULL: 403,

  // Friend Management
  R_ADD_FRIEND_OK: 911,
  R_ADD_FRIEND_NOT_OK: 912,
  R_ADD_FRIEND_ALREADY_EXISTS: 913,
  R_INVITE_FRIEND_OK: 921,
  R_INVITE_FRIEND_NOT_OK: 922,
  R_INVITE_ALREADY_SENT: 923,
  R_ACCEPT_INVITE_OK: 931,
  R_ACCEPT_INVITE_NOT_OK: 932,
  R_REJECT_INVITE_OK: 941,
  R_REJECT_INVITE_NOT_OK: 942,
  R_GET_INVITES_OK: 951,
  R_GET_INVITES_NOT_OK: 952,
  R_GET_FRIEND_LIST_OK: 961,
  R_GET_FRIEND_LIST_NOT_OK: 962
} as const

// Header size
export const HEADER_SIZE = 5 // 2 (len) + 1 (ver) + 2 (type)
